# Generated by Django 4.2.10 on 2024-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationHub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
