# Generated by Django 5.0.6 on 2024-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'VenueStation_venue',
            },
        ),
    ]
